name: Unit tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.15.x', 'tip' ]
    steps:
      - name: Install Go
        run: |
          curl -sL https://raw.githubusercontent.com/maxatome/install-go/v2.0/install-go.pl |
            perl - ${{ matrix.go-version }} $HOME/go
          go version

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Build
        run: go build ./...

      - name: Vet
        run: go vet ./...

      - name: test
        run: go test ./...
